"""Update User model for google scope

Revision ID: b804cf699ec7
Revises: 582ce189462b
Create Date: 2024-09-20 00:24:12.230955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b804cf699ec7'
down_revision: Union[str, None] = '582ce189462b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_google_sub', ['google_sub'])  # Указано имя ограничения
        batch_op.drop_column('auth0_sub')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_sub', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('uq_google_sub', 'users', type_='unique')  # Указано имя ограничения
        batch_op.drop_column('google_sub')
    # ### end Alembic commands ###
