"""Update User model

Revision ID: fe0e4b6144b1
Revises: e824d36a56de
Create Date: 2024-09-19 23:30:12.305741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0e4b6144b1'
down_revision: Union[str, None] = 'e824d36a56de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
